name: Test grammar

on: [push, pull_request]

jobs:
  build:
    name: Test grammar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      - name: Install dependencies
        run: npm install

      - name: Test corpus
        run: npm test

      - name: Test examples
        run: |
          script/fetch-examples
          script/parse-examples
